services:
  postgres:
    image: postgres:16
    container_name: news_aggregator_db
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-aggregator}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-aggregator_pass}
      POSTGRES_DB: ${POSTGRES_DB:-news_aggregator}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
